### ISSUE TITLE
install errors windows 10-64bit installer

### ISSUE THREAD

**Issue by Tecko71** [TheAppgineer/roon-extension-manager-packaging#1]
npm WARN deprecated node-uuid@1.4.8: Use uuid module instead
npm WARN ws@7.4.4 requires a peer of bufferutil@^4.0.1 but none is installed. You must install peer dependencies yourself.
npm WARN ws@7.4.4 requires a peer of utf-8-validate@^5.0.2 but none is installed. You must install peer dependencies yourself.

+ roon-extension-manager@0.11.9
added 54 packages from 63 contributors in 11.499s
Installing Updater...
+ roon-extension-manager-updater@0.4.1
added 47 packages from 57 contributors in 6.83s

Starting service...
roon-extension-manager: Unexpected status SERVICE_PAUSED in response to START control.

**Comment by JanKoudijs** [comment]
Can you check the Windows Event Viewer for errors on the nssm Source?
I don't get errors myself.

![image](https://user-images.githubusercontent.com/26183008/112727611-8ef54c80-8f23-11eb-823f-d01f9046fd87.png)

**Comment by Tecko71** [comment]
Nssm event 1030: Registry key AppDirectory is unset for service roon-extension-manager. Assuming startup directory C:\Windows.
                    1034: Service roon-extension-manager ran for less than 1500 milliseconds. Restart will be delayed by 256000 
                     milliseconds.

**Comment by JanKoudijs** [comment]
Ok, it is the second message that I don't see in my setup. It looks like the `.bat` file terminates immediately. What happens if you run it in a command window?

```
cd %AppData%/RoonExtensions
roon-extension-manager.bat
```

**Comment by Tecko71** [comment]
than the install works, i think:

2021-03-27T19:22:55.155Z - Inf: Installed: roon-extension-repository (0.3.17)
{ 'roon-extension-manager-updater': '0.4.1',
  'roon-extension-manager': '0.11.9',
  'roon-extension-repository': '0.3.17' }
{}
2021-03-27T19:22:55.160Z - Inf: Extension Repository loaded

**Comment by JanKoudijs** [comment]
Yes, there is something going on with the service that makes it work for some but not for others, I hoped that the Event Viewer would give a clearer hint. As I cannot reproduce the problem, I decided to move away from the Windows installer for the 1.0 version of the Extension Manager that I announced recently. My advice is to start using a Raspberry Pi to run your extensions or setup a Linux VM.

You can read about 1.0 in [this thread](https://community.roonlabs.com/t/important-information-for-extension-manager-users/151313) on the Roon Forum.
